package com.qinhailin.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.jfinal.plugin.activerecord.Model;
import com.qinhailin.common.model.annotation.Table;
import com.qinhailin.common.routes.ClassSearcher;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("file_uploaded", "id", FileUploaded.class);
		arp.addMapping("sys_function", "id", SysFunction.class);
		arp.addMapping("sys_org", "id", SysOrg.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_role_function", "id", SysRoleFunction.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("sys_user_role", "id", SysUserRole.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("data_dictionary", "id", DataDictionary.class);
		arp.addMapping("data_dictionary_value", "id", DataDictionaryValue.class);
		
		annotationTable(arp);
	}
	
	/**
	 * 注解配置model
	 * @param arp
	 * @author qinhailin
	 * @date 2020-08-18
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public static void annotationTable(ActiveRecordPlugin arp){
		List<Class<? extends Model>> modelClasses = ClassSearcher.of(Model.class).setTargetName("*.class").search();
		 Table table = null;
		 for (Class model : modelClasses) {
			 table = (Table) model.getAnnotation(Table.class);
			 if (table != null) {      	
	           	arp.addMapping(table.tableName(), table.primaryKey(), model);
			 }
        }
	}
}

