package com.qinhailin.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.qinhailin.common.model.annotation.TableScanner;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("file_uploaded", "id", FileUploaded.class);
		arp.addMapping("sys_function", "id", SysFunction.class);
		arp.addMapping("sys_org", "id", SysOrg.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_role_function", "id", SysRoleFunction.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("sys_user_role", "id", SysUserRole.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("data_dictionary", "id", DataDictionary.class);
		arp.addMapping("data_dictionary_value", "id", DataDictionaryValue.class);
		
		annotationTable(arp);
	}
	
	/**
	 * 注解配置model
	 * @param arp
	 * @author qinhailin
	 * @date 2020-08-18
	 */
	public static void annotationTable(ActiveRecordPlugin arp){
		TableScanner tableScanner=new TableScanner("com.qinhailin",arp);
		tableScanner.scan();
	}
}

